//This is test suite
const selectors = require("../pageObjects/selector.json")
const values = require("../testdata/fieldvalues.json")
const baseUrl = "https://www.securian.com/insights-tools/retirement-calculator.html"

describe("retirement calculator tests", function () {
    it("fill in the require fileds and submit", async () => {
      await  browser.url(baseUrl)
      expect(browser).toHaveUrl("https://www.securian.com/insights-tools/retirement-calculator.html")
      await browser.$(selectors.inputBoxes.currentAge).addValue(values.currentAge)
      await browser.$(selectors.inputBoxes.retirement).addValue(values.retirement)
      await browser.$(selectors.inputBoxes.currentAnnualIncome).click()
      await browser.$(selectors.inputBoxes.currentAnnualIncome).addValue(values.currentAnnualIncome)
      await browser.$(selectors.inputBoxes.spouseAnnualIncome).click()
      await browser.$(selectors.inputBoxes.spouseAnnualIncome).addValue(values.spouseAnnualIncome)
      await browser.$(selectors.inputBoxes.currentRetireSavings).click()
      await browser.$(selectors.inputBoxes.currentRetireSavings).addValue(values.currentRetireSavings)
      await browser.$(selectors.inputBoxes.currentRetireContribution).click()
      await browser.$(selectors.inputBoxes.currentRetireContribution).addValue(values.currentRetireContribution)
      await browser.$(selectors.inputBoxes.annualRetirementContributionIncrease).click()
      await browser.$(selectors.inputBoxes.annualRetirementContributionIncrease).addValue(values.annualRetirementContributionIncrease)
      await browser.$(selectors.inputBoxes.socialSecurityIncome).waitForDisplayed()
      await browser.$(selectors.inputBoxes.socialSecurityIncome).click()
      await browser.$(selectors.inputBoxes.socialSecurityOverride).waitForDisplayed()
      await browser.$(selectors.inputBoxes.socialSecurityOverride).click()
      await browser.$(selectors.inputBoxes.socialSecurityOverride).addValue(values.socialSecurityOverride)
      await browser.$(selectors.buttons.adjustDefaultValuesButton).click()
      await browser.$(selectors.inputBoxes.additionalOtherIncome).waitForDisplayed()
      await browser.$(selectors.inputBoxes.additionalOtherIncome).click()
      await browser.$(selectors.inputBoxes.additionalOtherIncome).addValue(values.additionalOtherIncome)
      await browser.$(selectors.inputBoxes.numberOfYearsRetirement).click()
      await browser.$(selectors.inputBoxes.numberOfYearsRetirement).setValue(values.numberOfYearsRetirement)
      await browser.$(selectors.inputBoxes.percentOfinFalAnnualIncomeDesired).click()
      await browser.$(selectors.inputBoxes.percentOfinFalAnnualIncomeDesired).addValue(values.percentOfinFalAnnualIncomeDesired)
      await browser.$(selectors.inputBoxes.preRetirementInvestmentReturn).addValue(values.preRetirementInvestmentReturn)
      await browser.$(selectors.inputBoxes.postRetirementInvestmentReturn).addValue(values.postRetirementInvestmentReturn)
      await browser.$(selectors.buttons.saveButton).click()
      await browser.$(selectors.buttons.calculatorButton).waitForDisplayed()
      await browser.$(selectors.buttons.calculatorButton).click()
      const elem = await $(selectors.results)
      elem.waitForDisplayed()
      await expect(elem).toBeDisplayed()
    });
});
